### ISSUE TITLE
Add base models

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-instance-tbf#5]
Add a first set of models, similar to/extending Frischmuth, modeled on FRBR/FRBRoo + CIDOC CRM (?) entities:

- [ ] Work
- [ ] Expression (?)
- [ ] Manifestation (?)
- [ ] Item
- [ ] Person -> inherit from [E21_Person](https://github.com/acdh-oeaw/apis-core-rdf/blob/1323d33e0bbbaae879acb5a13a4ee70ae221712d/apis_core/apis_entities/abc.py#L13)
- [ ]  Group -> inherit from [E74_Group](https://github.com/acdh-oeaw/apis-core-rdf/blob/1323d33e0bbbaae879acb5a13a4ee70ae221712d/apis_core/apis_entities/abc.py#L39)
- [ ] Place -> inherit from [E53_Place](https://github.com/acdh-oeaw/apis-core-rdf/blob/1323d33e0bbbaae879acb5a13a4ee70ae221712d/apis_core/apis_entities/abc.py#L27)

Notes on/differences to Frischmuth:
Frischmuth collapses `Manifestation` into `Expression` and doesn't use `Item` at all; `Organisation` (Körperschaft) subsumes `Group` and `Corporate/Legal Body`; `Person` and `Organisation` don't have a common ancestor (anymore).

**Comment by koeaw** [comment]
@sennierer I think you mentioned `Group` as superclass for `Person` and Körperschaft; the hierarchy above is what the FRBRoo 2.4 doc suggests. Not sure about the last one, F11 Corporate Body (there's also E40 Legal Body, which is considered a subclass of F11).

Should I use the above or something else?

**Comment by koeaw** [comment]
> Should I use the above or something else?

Updated Person, Group, Place as discussed; leaving aside Expression, Manifestation until there's more info.

**Comment by sennierer** [comment]
just discussed this with Daniel. We start with the full 4 levels (work, expression, manifestation and item) as you suggested

**Comment by koeaw** [comment]
> just discussed this with Daniel. We start with the full 4 levels (work, expression, manifestation and item) as you suggested

Thx!
